CREATE TABLE IF NOT EXIST users(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  email text NOT NULL CHECK (email <> ''),
  password text NOT NULL,
  role integer NOT NULL
);

CREATE TABLE IF NOT EXIST books(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL CHECK (title <> ''),
  author text NOT NULL,
  genre text NOT NULL,
  copies integer NOT NULL
);

CREATE TABLE IF NOT EXIST reserves(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  bookId integer REFERENCES books(id),
  userId integer REFERENCES users(id),
  copiesRequested integer NOT NULL,
  requestedDate date NOT NULL,
  deliveryDate date
);
